sonar.projectKey=jooservices_go-jabledownloader
sonar.projectName=go-jabledownloader
sonar.organization=jooservices
sonar.sources=cmd,internal
sonar.tests=cmd,internal
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=build/coverage/coverage.out
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
sonar.exclusions=**/*_test.go,**/testdata/**,**/.github/**,**/bin/**,**/dist/**,**/.cache/**,build/**
